en:
  title: "blog.oddbit.com"
  copyright: "Lars Kellogg-Stedman"
  readMore: "read more"
  params:
    logo:
      logoText: "the odd bit blog"
      logoHomeLink: "/"
      subtitle: "one of these things is not like the others"

  menu:
    main:
      - identifier: "home"
        name: "/"
        url: "/"
        weight: 1
      - identifier: "about"
        name: "/about"
        url: "https://oddbit.com"
        weight: 2
      - identifier: "posts"
        name: "/posts"
        url: "/posts"
        weight: 3
      - identifier: "tags"
        name: "/tags"
        url: "/tags"
        weight: 4
      - identifier: "archive"
        name: "/archive"
        url: "/archive"
        weight: 5
      - identifier: "feed"
        name: "/feed"
        url: "/rss.xml"
        weight: 6
      - identifier: "github"
        name: "→Github"
        url: "https://github.com/larsks"
        weight: 10
      - identifier: "twitter"
        name: "→Twitter"
        url: "https://twitter.com/larsks"
        weight: 10
      - identifier: "mastodon"
        name: "→Mastodon"
        url: "https://hachyderm.io/@larsks"
        weight: 10
