name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

  # republish every morning at 10:00 UTC so that posts with future
  # dates are handled automatically.
  schedule:
    - cron: 0 10 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.139.0"
          extended: true

      - name: Build
        run: |
          hugo mod get -u ./...
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
